export class web {
    address: object = {
        "Q": "https://qzone.qq.com",
        "W": "https://wx.qq.com",
        "E": "void 0",
        "R": "void 0",
        "T": "https://www.tmall.com",
        "Y": "http://www.youku.com",
        "U": "void 0",
        "I": "http://www.iqiyi.com",
        "O": "https://open.163.com",
        "P": "https://www.python.org",
        "A": "https://www.angular.cn",
        "S": "https://www.sogou.com",
        "D": "http://www.dangdang.com",
        "F": "void 0",
        "G": "http://www.google.com",
        "H": "void 0",
        "J": "https://www.jd.com",
        "K": "void 0",
        "L": "http://lol.qq.com",
        "Z": "void 0",
        "X": "http://www.mi.com",
        "C": "void 0",
        "V": "void 0",
        "B": "http://www.baidu.com",
        "N": "https://nodejs.org/en",
        "M": "http://map.baidu.com"
    }
}